[2021-05-25 19:26:14,827] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: covid19_cases_Jordan.Get_COVID19_Cases_For_Jordan_2020_Now 2021-05-25T19:25:12.633520+00:00 [queued]>
[2021-05-25 19:26:14,854] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: covid19_cases_Jordan.Get_COVID19_Cases_For_Jordan_2020_Now 2021-05-25T19:25:12.633520+00:00 [queued]>
[2021-05-25 19:26:14,854] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-05-25 19:26:14,854] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-05-25 19:26:14,854] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-05-25 19:26:14,869] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): Get_COVID19_Cases_For_Jordan_2020_Now> on 2021-05-25T19:25:12.633520+00:00
[2021-05-25 19:26:14,874] {standard_task_runner.py:52} INFO - Started process 162 to run task
[2021-05-25 19:26:14,876] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'covid19_cases_Jordan', 'Get_COVID19_Cases_For_Jordan_2020_Now', '2021-05-25T19:25:12.633520+00:00', '--job-id', '4', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/workflow.py', '--cfg-path', '/tmp/tmp4iumw7z5', '--error-file', '/tmp/tmp3ftblvci']
[2021-05-25 19:26:14,878] {standard_task_runner.py:77} INFO - Job 4: Subtask Get_COVID19_Cases_For_Jordan_2020_Now
[2021-05-25 19:26:14,913] {logging_mixin.py:104} INFO - Running <TaskInstance: covid19_cases_Jordan.Get_COVID19_Cases_For_Jordan_2020_Now 2021-05-25T19:25:12.633520+00:00 [running]> on host 4e0af5d83701
[2021-05-25 19:26:15,188] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=waed
AIRFLOW_CTX_DAG_ID=covid19_cases_Jordan
AIRFLOW_CTX_TASK_ID=Get_COVID19_Cases_For_Jordan_2020_Now
AIRFLOW_CTX_EXECUTION_DATE=2021-05-25T19:25:12.633520+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-25T19:25:12.633520+00:00
[2021-05-25 19:26:15,190] {taskinstance.py:1455} ERROR - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/workflow.py", line 77, in Get_All_Data
    for Day in Get_Data_Rang():
TypeError: 'NoneType' object is not iterable
[2021-05-25 19:26:15,210] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=covid19_cases_Jordan, task_id=Get_COVID19_Cases_For_Jordan_2020_Now, execution_date=20210525T192512, start_date=20210525T192614, end_date=20210525T192615
[2021-05-25 19:26:15,290] {local_task_job.py:146} INFO - Task exited with return code 1
